// This code was generated by Hypar.
// Edits to this code will be overwritten the next time you run 'hypar init'.
// DO NOT EDIT THIS FILE.

using Elements;
using Elements.GeoJSON;
using Elements.Geometry;
using Hypar.Functions;
using Hypar.Functions.Execution;
using Hypar.Functions.Execution.AWS;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.Collections.Generic;

namespace RhinoHead
{
    public class RhinoHeadOutputs: ResultsBase
    {
		/// <summary>
		/// The number of objects in the Rhino model.
		/// </summary>
		[JsonProperty("Objects")]
		public double Objects {get;}


        
        /// <summary>
        /// Construct a RhinoHeadOutputs with default inputs.
        /// This should be used for testing only.
        /// </summary>
        public RhinoHeadOutputs() : base()
        {

        }


        /// <summary>
        /// Construct a RhinoHeadOutputs specifying all inputs.
        /// </summary>
        /// <returns></returns>
        [JsonConstructor]
        public RhinoHeadOutputs(double objects): base()
        {
			this.Objects = objects;

		}

		public override string ToString()
		{
			var json = JsonConvert.SerializeObject(this);
			return json;
		}
	}
}